version: '3.7'

services:
  nginx:
    image: nginx:latest  # or a specific version
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
      - ./certs/certificate.crt:/etc/nginx/ssl/certificate.crt # Mount the host SSL directory
      - ./certs/private.key:/etc/nginx/ssl/private.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config
    ports:
      - 80:80
      - 3377:443
    restart: unless-stopped  # Automatically restart unless manually stopped
